### ISSUE TITLE
Groupmanager shows groups from unassigned soldiers

### ISSUE THREAD

**Issue by oldLucke** [TaskForce47/TF47-Corescripts#23]
![image](https://user-images.githubusercontent.com/30210892/90683029-34499300-e266-11ea-86a2-f4d74f19234d.png)
these groups are the default group that each units gets when joining the game

**Comment by Desty84** [comment]
GroupManager is im Mod
und das sind keine Unassgined sondern die Base Def AI wenn ich mich nicht Irre
